###########################################################################
#  Copyright 2020 DataRobot Inc. All Rights Reserved.                     #
#                                                                         #
#  This file is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES       #
#  OR CONDITIONS OF ANY KIND, express or implied.                         #
###########################################################################
# https://docs.aws.amazon.com/systems-manager/latest/userguide/sysman-paramstore-access.html
AWSTemplateFormatVersion: 2010-09-09
Description: Build out the IAM role allowing us to read the S3 bucket and EC2 instances
Parameters:
  MainStack:
    Type: String
  S3Bucket:
    Type: String
    Description: CloudFormation repository S3 bucket name

Resources: 
  DataRobotEnterpriseIAMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      Path: /

  InstanceProfile:
    Type: 'AWS::IAM::InstanceProfile'
    Properties:
      Path: /
      Roles:
        - !Ref DataRobotEnterpriseIAMRole

  RolePolicies:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: DataRobotEnterpriseIAMPolicy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - 'ec2:DescribeInstances'
              - 'ec2:DescribeInstanceStatus'
              - 'elasticloadbalancing:*'
              - 'lambda:CreateFunction'
              - 'lambda:DeleteFunction'
              - 'lambda:GetFunctionConfiguration'
              - 'ssm:DescribeParameters'
            Resource:
              - '*'

          - Effect: Allow
            Action:
              - 's3:ListAllMyBuckets'
              - 's3:Get*'
            Resource:
              - !Sub 'arn:aws:s3:::${S3Bucket}'
              - !Sub 'arn:aws:s3:::${S3Bucket}/*'

          - Effect: Allow
            Action:
              - 'cloudformation:DescribeStacks'
              - 's3:PutObject'
              - 's3:ListBucketMultipartUploads'
              - 's3:AbortMultipartUpload'
              - 's3:ListBucketVersions'
              - 's3:ListBucket'
              - 's3:DeleteObject'
              - 's3:GetBucketLocation'
              - 's3:ReplicateDelete'
              - 's3:ListMultipartUploadParts'
              - 'ssm:PutParameter'
              - 'ssm:GetParameter'
              - 'ssm:DeleteParameter'
            Resource:
              - arn:aws:ssm:*:*:parameter/*/datarobot-public-key
              - !Sub 'arn:aws:s3:::${S3Bucket}'
              - !Sub 'arn:aws:s3:::${S3Bucket}/*'
              - !Sub 'arn:aws:cloudformation:*:*:stack/${MainStack}/*'

          - Effect: Allow
            Action:
              - 'ec2:CreateTags'
            Resource:
              - arn:aws:ec2:*:*:volume/*

      Roles:
        - !Ref DataRobotEnterpriseIAMRole      

Outputs:
  InstanceProfile:
    Description: InstanceProfile for DR EC2 instances
    Value:
      Ref: InstanceProfile