###########################################################################
#  Copyright 2020 DataRobot Inc. All Rights Reserved.                     #
#                                                                         #
#  This file is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES       #
#  OR CONDITIONS OF ANY KIND, express or implied.                         #
###########################################################################

AWSTemplateFormatVersion: "2010-09-09"
Description: Test stack used to confirm some of the permissions for DataRobot
Parameters:
  MainStack:
    Type: String
  S3Bucket:
    Type: String
    Description: CloudFormation repository S3 bucket name
  DRVersion:
    Type: String
    Description: DataRobot version to install
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})'
  SSHKey:
    Type: "AWS::EC2::KeyPair::KeyName"
    Description: Key pair to use for connectivity
  Subnet:
    Type: "AWS::EC2::Subnet::Id"
    Description: Subnet for cluster
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: Virtual Private Cloud Id
  Region:
    Type: String
    Description: Region to host cluster
    AllowedValues: [ "ap-south-1", "eu-west-1", "eu-west-2", "eu-west-3", "eu-north-1", "ap-northeast-1", "ap-northeast-2", "sa-east-1", "ca-central-1", "ap-southeast-1", "ap-southeast-2", "eu-central-1", "us-east-1", "us-east-2", "us-west-1", "us-west-2" ]
    Default: us-east-1
  ClusterType:
    Type: String
  OperatingSystem:
    Type: String
    Description: Use RHEL or centos
    AllowedValues: [ "rhel", "centos" ]
    Default: rhel

# Note: Anything with a 8 char id is RHEL 7.5, where 17 char id's are rhel 7.6
# Note 2: Finish the centos list
Mappings: 
  OSRegionMap: 
    ap-northeast-1:
      rhel: "ami-08419d23bf91152e4"
      centos: ""
    ap-northeast-2:
      rhel: "ami-3eee4150"
      centos: ""
    ap-south-1:
      rhel: "ami-5b673c34"
      centos: ""
    ap-southeast-1:
      rhel: "ami-76144b0a"
      centos: ""
    ap-southeast-2:
      rhel: "ami-67589505"
      centos: ""
    ca-central-1:
      rhel: "ami-49f0762d"
      centos: ""
    eu-central-1:
      rhel: "ami-c86c3f23"
      centos: ""
    eu-north-1:
      rhel: "ami-95b53beb"
      centos: ""
    eu-west-1:
      rhel: "ami-0e12cbde3e77cbb98"
      centos: ""
    eu-west-2:
      rhel: "ami-7c1bfd1b"
      centos: ""
    eu-west-3:
      rhel: "ami-5026902d"
      centos: ""
    sa-east-1:
      rhel: "ami-b0b7e3dc"
      centos: ""
    us-east-1:
      rhel: "ami-011b3ccf1bd6db744"
      centos: ""
    us-east-2:
      rhel: "ami-0b500ef59d8335eee"
      centos: ""
    us-west-1:
      rhel: "ami-0ec1ad91f200c15a8"
      centos: ""
    us-west-2:
      rhel: "ami-036affea69a1101c9"
      centos: ""

Resources:
  EC2Instance:
    Type: "AWS::EC2::Instance"

    Properties: 
      ImageId: !FindInMap
        - OSRegionMap
        - !Ref 'AWS::Region'
        - !Ref OperatingSystem
      InstanceType: t2.micro
      KeyName: !Ref SSHKey
      SubnetId: !Ref Subnet
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            DeleteOnTermination: true
            VolumeSize: 20
      UserData:
        Fn::Base64: !Sub |
          #!/bin/sh

          # Debug
          MainStack = ${MainStack}
          AWS::StackName = ${AWS::StackName}
          S3Bucket = ${S3Bucket}
          DRVersion = ${DRVersion}
          SSHKey = ${SSHKey}
          VpcId = ${VpcId}
          Subnet = ${Subnet}
          InstanceType = t2.micro
          ClusterType = ${ClusterType}
          OperatingSystem = ${OperatingSystem}
          Region = ${Region}
          AWS::Region = ${AWS::Region}

Outputs:
  S3Bucket:
    Description: CloudFormation repository S3 bucket name
    Value: !Ref S3Bucket
  DRVersion:
    Description: DataRobot version to install
    Value: !Ref DRVersion
  SSHKey:
    Description: Key pair to use for connectivity
    Value: !Ref SSHKey
  Subnet:
    Description: Subnet for cluster
    Value: !Ref Subnet
  VpcId:
    Description: Virtual Private Cloud Id
    Value: !Ref VpcId
  Region:
    Description: Region to host cluster
    Value: !Ref Region
  ClusterType:
    Description: Type of cluster to build.
    Value: !Ref ClusterType
  InstanceId:
    Description: "InstanceId of the newly created EC2 instance"
    Value: !Ref EC2Instance
  PrivateIP:
    Description: "PrivateIP IP address of the newly created EC2 instance"
    Value: !GetAtt EC2Instance.PrivateIp
